DefaultContentLanguage = "en"
baseURL = "https://www.elishatan.com/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
summarylength = 10
title = "Elisha Tan | DevRel, Community Builder, Founder"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[params]
author = "Elisha Tan"
customCss = []
customJs = []
description = "Elisha is a Developer Community Programs Manager at Facebook, the Founder of TechLadies, and the Co-founder of DevRelFolks Asia. She is passionate about bringing people together to solve big problems."
favicon = "favicons/"
images = "images/og_image.jpg"
keywords = ""
mainSections = ["post"]
profilePicture = "images/profile.png"
title = "Elisha Tan | DevRel, Community Builder, Founder"
[params.math]
enable = false
use = "katex"
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/elishatan/"
[[params.socialIcons]]
icon = "fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/elishatan88"
[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/elishatan"
[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/elishatan"
[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:elisha.tan@gmail.com"
