DefaultContentLanguage = "en"
baseURL = "https://clever-galileo-741632.netlify.app/"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
summarylength = 10
title = "Website of Jane Doe"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
author = "Jane Doe"
customCss = []
customJs = []
description = "Call me <b>Jane</b>"
favicon = "favicons/"
images = ["images/site-feature-image.png"]
keywords = ""
mainSections = ["post"]
profilePicture = "images/profile.jpg"
title = "I'm Jane Doe"
[params.math]
enable = false
use = "katex"
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"
[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"
[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:mail@alexbilz.com"
